sudo: false

os:
  - windows
  - linux
  - osx

language: node_js

node_js:
  - lts/*

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - npm run build
  - npm run coverage
  - npx commitlint-travis

after_script:
  - npx codecov
